apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: my-service-v2
  namespace: my-apps
spec:
  awsName: my-service-v2-virtual-node
  podSelector:
    matchLabels:
      app: my-app-2
  listeners:
    - portMapping:
        port: 8080
        protocol: http  
  serviceDiscovery:
    dns:
      hostname: my-service-v2.my-apps.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: my-service-v2
spec:
  awsName: my-service-v2-virtual-router
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: route-to-my-service-v2
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef: 
                name: my-service-v2
              weight: 1
        retryPolicy:
            maxRetries: 2
            perRetryTimeout:
                unit: ms
                value: 2000
            httpRetryEvents:
                - server-error
                - client-error
                - gateway-error
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: my-service-v2
  namespace: my-apps
spec:
  awsName: my-service-v2
  provider:
    virtualRouter:
        virtualRouterRef:
            name: my-service-v2