---
apiVersion: v1
kind: Service
metadata:
  name: ingress-gw
  namespace: my-apps
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088
      name: http
  selector:
    app: ingress-gw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-gw
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-gw
  template:
    metadata:
      labels:
        app: ingress-gw
    spec:
      serviceAccountName: my-app-envoy-proxies
      securityContext:
        fsGroup: 65534
      containers:
        - name: envoy
          image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.21.0.0-prod
          ports:
            - containerPort: 8088
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualGateway
metadata:
  name: ingress-gw
  namespace: my-apps
spec:
  namespaceSelector:
    matchLabels:
      gateway: ingress-gw
  podSelector:
    matchLabels:
      app: ingress-gw
  listeners:
    - portMapping:
        port: 8088
        protocol: http
  logging:
    accessLog:
      file:
        path: /dev/stdout
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-my-app-v1
  namespace: my-apps
spec:
  httpRoute:
    match:
      prefix: "/"
      headers:
        - name: app_version
          match:
            exact: v1
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: my-service-v1
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-my-app-v2
  namespace: my-apps
spec:
  httpRoute:
    match:
      prefix: "/"
      headers:
        - name: app_version
          match:
            exact: v2
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: my-service-v2
---