apiVersion: v1
kind: Service
metadata:
  name: my-service-v2
  namespace: my-apps
  labels:
    app: my-app-2
spec:
  selector:
    app: my-app-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-v2
  namespace: my-apps
  labels:
    app: my-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      serviceAccountName: my-service-v2
      containers:
      - name: my-app-v2
        image: 715052932111.dkr.ecr.us-west-2.amazonaws.com/appmesh-test-service:v2
        ports:
        - containerPort: 8080